
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 27 08:15:10 CET 2026
//----------------------------------------------------

package kyr.parser;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int INTEGER = 10;
  public static final int BOOLEAN_KW = 8;
  public static final int INTEGER_KW = 7;
  public static final int BOOLEAN = 12;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int ASSIGN_OP = 9;
  public static final int error = 1;
  public static final int SEMICOLON = 4;
  public static final int PRINT = 5;
  public static final int IDENTIFIER = 13;
  public static final int VARIABLES_KW = 6;
  public static final int END = 3;
  public static final int BEGIN = 2;
}

